name: Build and Script
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: "executing remote ssh commands using ssh key"
      uses: PNSQL-2022-Workshop/DevSecOps_Workshop@master
      with:
        host: ${{ secrets.HOST }}'
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
